# -*- coding: utf-8 -*-
"""TASK-1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17QjDhFkY7X03LpNDl4wBGCT3CBA7wpvv
"""

#IMPORT NECESSARY LIBRARIES
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# To load a data set
df =pd.read_csv("/content/Iris.csv")

print(df.head())
print(df.tail())

print(df.columns)

#Overview
print("Shape:", df.shape)
print(df.info())
print("Missing values:", df.isnull().sum())
print(df.describe())

# Univariate Analysis
df.hist(figsize=(10, 8), bins=20, color='skyblue', edgecolor='black')
plt.suptitle("Histograms of Numerical Features", fontsize=16)
plt.show()

plt.figure(figsize=(12, 6))
sns.boxplot(data=df.iloc[:, :-1], palette="Set3")
plt.title("Boxplots of Numerical Features", fontsize=16)
plt.show()

# Multivariate Analysis
sns.pairplot(df, hue='Species', palette='husl')
plt.show()

corr_matrix = df.iloc[:, :-1].corr()
plt.figure(figsize=(8, 6))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.2f', square=True)
plt.title("Heatmap of Feature Correlations", fontsize=16)
plt.show()

# Outlier Detection
Q1 = df['SepalLengthCm'].quantile(0.25)
Q3 = df['SepalLengthCm'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = df[(df['SepalLengthCm'] < lower_bound) | (df['SepalLengthCm'] > upper_bound)]
print("Outliers in 'SepalLengthCm':")
print(outliers)

# Additional Visualizations
sns.countplot(data=df, x='Species', palette='pastel')
plt.title("Count of Each Species", fontsize=16)
plt.show()

sns.lmplot(data=df, x='SepalLengthCm', y='PetalLengthCm', hue='Species', aspect=1.5, markers=['o', 's', 'D'])
plt.title("Scatterplot with Regression Line", fontsize=16)
plt.show()